-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 20:52:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sooters_dev
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sooters_dev` ;

SET GLOBAL log_bin_trust_function_creators = 1;

-- -----------------------------------------------------
-- Schema sooters_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sooters_dev` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sooters_dev` ;

-- -----------------------------------------------------
-- Table `sooters_dev`.`_sequence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sooters_dev`.`_sequence` ;

CREATE TABLE IF NOT EXISTS `sooters_dev`.`_sequence` (
  `seq_name` VARCHAR(4) NOT NULL,
  `seq_val` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`seq_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sooters_dev`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sooters_dev`.`addresses` ;

CREATE TABLE IF NOT EXISTS `sooters_dev`.`addresses` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Number` VARCHAR(16) NOT NULL,
  `Street` VARCHAR(64) NOT NULL,
  `City` VARCHAR(64) NOT NULL,
  `PostalCode` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sooters_dev`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sooters_dev`.`customers` ;

CREATE TABLE IF NOT EXISTS `sooters_dev`.`customers` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(32) NOT NULL,
  `LastName` VARCHAR(32) NOT NULL,
  `PhoneNumber` VARCHAR(32) NULL DEFAULT NULL,
  `Email` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sooters_dev`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sooters_dev`.`locations` ;

CREATE TABLE IF NOT EXISTS `sooters_dev`.`locations` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(32) NOT NULL,
  `Address` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Address_UNIQUE` (`Address` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  CONSTRAINT `locations_addresses`
    FOREIGN KEY (`Address`)
    REFERENCES `sooters_dev`.`addresses` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sooters_dev`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sooters_dev`.`employees` ;

CREATE TABLE IF NOT EXISTS `sooters_dev`.`employees` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(64) NOT NULL,
  `Active` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  `PrimaryLocation` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `employees_locations_idx` (`PrimaryLocation` ASC) VISIBLE,
  CONSTRAINT `employees_locations`
    FOREIGN KEY (`PrimaryLocation`)
    REFERENCES `sooters_dev`.`locations` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sooters_dev`.`customer_notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sooters_dev`.`customer_notes` ;

CREATE TABLE IF NOT EXISTS `sooters_dev`.`customer_notes` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Customer` INT UNSIGNED NOT NULL,
  `Creator` INT UNSIGNED NOT NULL,
  `DateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Note` LONGTEXT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `customer_notes_customers_idx` (`Customer` ASC) VISIBLE,
  INDEX `customer_notes_employees_idx` (`Creator` ASC) VISIBLE,
  CONSTRAINT `customer_notes_customers`
    FOREIGN KEY (`Customer`)
    REFERENCES `sooters_dev`.`customers` (`ID`),
  CONSTRAINT `customer_notes_employees`
    FOREIGN KEY (`Creator`)
    REFERENCES `sooters_dev`.`employees` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sooters_dev`.`order_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sooters_dev`.`order_types` ;

CREATE TABLE IF NOT EXISTS `sooters_dev`.`order_types` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sooters_dev`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sooters_dev`.`orders` ;

CREATE TABLE IF NOT EXISTS `sooters_dev`.`orders` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EnvelopeID` INT UNSIGNED NULL DEFAULT NULL,
  `CurrentLocation` INT UNSIGNED NOT NULL,
  `SourceLocation` INT UNSIGNED NOT NULL,
  `Receiver` INT UNSIGNED NOT NULL,
  `OrderType` INT UNSIGNED NOT NULL,
  `Customer` INT UNSIGNED NOT NULL,
  `DateReceived` DATE NOT NULL DEFAULT (curdate()),
  `DateDue` DATE NOT NULL,
  `DateComplete` DATE NULL DEFAULT NULL,
  `Paid` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `Rush` TINYINT UNSIGNED NOT NULL,
  `PickedUp` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `FormattedID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `orders_customers_idx` (`Customer` ASC) VISIBLE,
  INDEX `orders_employees_idx` (`Receiver` ASC) VISIBLE,
  INDEX `orders_order_types_idx` (`OrderType` ASC) VISIBLE,
  INDEX `orders_locations_idx` (`CurrentLocation` ASC) VISIBLE,
  INDEX `orders_locations2_idx` (`SourceLocation` ASC) VISIBLE,
  CONSTRAINT `orders_customers`
    FOREIGN KEY (`Customer`)
    REFERENCES `sooters_dev`.`customers` (`ID`),
  CONSTRAINT `orders_employees`
    FOREIGN KEY (`Receiver`)
    REFERENCES `sooters_dev`.`employees` (`ID`),
  CONSTRAINT `orders_locations`
    FOREIGN KEY (`CurrentLocation`)
    REFERENCES `sooters_dev`.`locations` (`ID`),
  CONSTRAINT `orders_locations2`
    FOREIGN KEY (`SourceLocation`)
    REFERENCES `sooters_dev`.`locations` (`ID`),
  CONSTRAINT `orders_order_types`
    FOREIGN KEY (`OrderType`)
    REFERENCES `sooters_dev`.`order_types` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sooters_dev`.`film_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sooters_dev`.`film_orders` ;

CREATE TABLE IF NOT EXISTS `sooters_dev`.`film_orders` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Prints` TINYINT UNSIGNED NOT NULL,
  `Digital` TINYINT UNSIGNED NOT NULL,
  `NumberOfRolls` INT UNSIGNED NOT NULL,
  `Color` TINYINT UNSIGNED NOT NULL,
  `Exposures` TINYINT UNSIGNED NOT NULL DEFAULT '24',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `film_orders_orders_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `film_orders_orders`
    FOREIGN KEY (`ID`)
    REFERENCES `sooters_dev`.`orders` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sooters_dev`.`framing_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sooters_dev`.`framing_orders` ;

CREATE TABLE IF NOT EXISTS `sooters_dev`.`framing_orders` (
  `ID` INT UNSIGNED NOT NULL,
  `Category` VARCHAR(10) NOT NULL,
  `Width` INT UNSIGNED NOT NULL,
  `Height` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `framing_orders_orders_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `framing_orders_orders`
    FOREIGN KEY (`ID`)
    REFERENCES `sooters_dev`.`orders` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sooters_dev`.`order_notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sooters_dev`.`order_notes` ;

CREATE TABLE IF NOT EXISTS `sooters_dev`.`order_notes` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `OrderID` INT UNSIGNED NOT NULL,
  `Creator` INT UNSIGNED NOT NULL,
  `DateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Note` LONGTEXT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `order_notes_employees_idx` (`Creator` ASC) VISIBLE,
  INDEX `order_notes_orders_idx` (`OrderID` ASC) VISIBLE,
  CONSTRAINT `order_notes_employees`
    FOREIGN KEY (`Creator`)
    REFERENCES `sooters_dev`.`employees` (`ID`),
  CONSTRAINT `order_notes_orders`
    FOREIGN KEY (`OrderID`)
    REFERENCES `sooters_dev`.`orders` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sooters_dev`.`photoshoot_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sooters_dev`.`photoshoot_types` ;

CREATE TABLE IF NOT EXISTS `sooters_dev`.`photoshoot_types` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sooters_dev`.`photoshoots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sooters_dev`.`photoshoots` ;

CREATE TABLE IF NOT EXISTS `sooters_dev`.`photoshoots` (
  `ID` INT UNSIGNED NOT NULL,
  `DateTime` DATETIME NOT NULL,
  `Type` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `photoshoots_photoshoot_types_idx` (`Type` ASC) VISIBLE,
  INDEX `photoshoots_orders_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `photoshoots_orders`
    FOREIGN KEY (`ID`)
    REFERENCES `sooters_dev`.`orders` (`ID`),
  CONSTRAINT `photoshoots_photoshoot_types`
    FOREIGN KEY (`Type`)
    REFERENCES `sooters_dev`.`photoshoot_types` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `sooters_dev` ;

-- -----------------------------------------------------
-- function getNextCustomSeq
-- -----------------------------------------------------

USE `sooters_dev`;
DROP function IF EXISTS `sooters_dev`.`getNextCustomSeq`;

DELIMITER $$
USE `sooters_dev`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `getNextCustomSeq`(
    sSeqName VARCHAR(4)
) RETURNS varchar(20) CHARSET utf8mb4
BEGIN
    DECLARE nLast_val INT; 
 
    SET nLast_val =  (SELECT seq_val
                          FROM _sequence
                          WHERE seq_name = sSeqName);
    IF nLast_val IS NULL THEN
        SET nLast_val = 1;
        INSERT INTO _sequence (seq_name,seq_val)
        VALUES (sSeqName,nLast_Val);
    ELSE
        SET nLast_val = nLast_val + 1;
        UPDATE _sequence SET seq_val = nLast_val
        WHERE seq_name = sSeqName;
    END IF; 
 
    SET @ret = (SELECT concat(sSeqName,'-',lpad(nLast_val,5,'0')));
    RETURN @ret;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_setCustomVal
-- -----------------------------------------------------

USE `sooters_dev`;
DROP procedure IF EXISTS `sooters_dev`.`sp_setCustomVal`;

DELIMITER $$
USE `sooters_dev`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_setCustomVal`(sSeqName VARCHAR(4),  nVal INT UNSIGNED)
BEGIN
    IF (SELECT COUNT(*) FROM _sequence  
            WHERE seq_name = sSeqName) = 0 THEN
        INSERT INTO _sequence (seq_name,seq_val)
        VALUES (sSeqName,nVal);
    ELSE
        UPDATE _sequence SET seq_val = nVal
        WHERE seq_name = sSeqName;
    END IF;
END$$

DELIMITER ;
USE `sooters_dev`;

DELIMITER $$

USE `sooters_dev`$$
DROP TRIGGER IF EXISTS `sooters_dev`.`order_id` $$
USE `sooters_dev`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `sooters_dev`.`order_id`
BEFORE INSERT ON `sooters_dev`.`orders`
FOR EACH ROW
BEGIN
   SET NEW.FormattedID = getNextCustomSeq(year(now()));
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
